apiVersion: v1alpha1
kind: "Role"
metadata:
  name: role-template-manage-posts
  labels:
    nebulacms.io/role-template: "true"
  annotations:
    rbac.authorization.nebulacms.io/dependencies: |
      [ "role-template-view-posts", "role-template-manage-snapshots", "role-template-manage-tags", "role-template-manage-categories", "role-template-post-author" ]
    rbac.authorization.nebulacms.io/module: "Posts Management"
    rbac.authorization.nebulacms.io/display-name: "Post Manage"
    rbac.authorization.nebulacms.io/ui-permissions: |
      ["system:posts:manage"]
rules:
  - apiGroups: [ "content.nebulacms.io" ]
    resources: [ "posts" ]
    verbs: [ "*" ]
  - apiGroups: [ "api.console.nebulacms.io" ]
    resources: [ "posts", "posts/publish", "posts/unpublish", "posts/recycle", "posts/content", "indices/post", "posts/revert-content" ]
    verbs: [ "create", "patch", "update", "delete", "deletecollection" ]
---
apiVersion: v1alpha1
kind: "Role"
metadata:
  name: role-template-view-posts
  labels:
    nebulacms.io/role-template: "true"
  annotations:
    rbac.authorization.nebulacms.io/dependencies: |
      [ "role-template-view-snapshots", "role-template-view-tags", "role-template-view-categories" ]
    rbac.authorization.nebulacms.io/module: "Posts Management"
    rbac.authorization.nebulacms.io/display-name: "Post View"
    rbac.authorization.nebulacms.io/ui-permissions: |
      ["system:posts:view"]
rules:
  - apiGroups: [ "content.nebulacms.io" ]
    resources: [ "posts" ]
    verbs: [ "get", "list" ]
  - apiGroups: [ "api.console.nebulacms.io" ]
    resources: [ "posts", "posts/head-content", "posts/release-content", "posts/snapshot", "posts/content" ]
    verbs: [ "get", "list" ]
